name: Bug Report
description: Create a bug report to help fix issues with OpenTabletDriver
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out the fields below adequately so that we have an easier time solving your issue. Thank you.

  - type: checkboxes
    id: wiki
    attributes:
      label: FAQ
      description: |
        Please make sure your issue isn't already covered on the [OpenTabletDriver Wiki](http://opentabletdriver.net/Wiki) and respective FAQ pages.
      options:
        - label: I have checked the wiki for my issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Sufficiently describe your bug here.
      placeholder: ex. OpenTabletDriver has stopped detecting my tablet...
    validations:
      required: true

  - type: input
    id: tablet
    attributes:
      label: Tablet Device
      placeholder: ex. Wacom CTL-472
    validations:
      required: true

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostic Information
      description: Export diagnostics and attach or paste below. In the GUI, click Help -> Export Diagnostics.
      render: JSON
    validations:
      required: true
