name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  linuxpublish:
    runs-on: ubuntu-latest
    name: Linux Publish
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Linux Publish
        env:
          runtime: linux-x64
          framework: net5
        run: |
          dotnet publish OpenTabletDriver.Daemon --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
          dotnet publish OpenTabletDriver.Console --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
          dotnet publish OpenTabletDriver.UX.Gtk --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
      - name: Copy Configurations
        run: |
          cp -vr ./OpenTabletDriver/Configurations/ build/linux-x64
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver linux-x64
          path: build/linux-x64

  macospublish:
    runs-on: ubuntu-latest
    name: MacOS Publish
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: MacOS Publish
        env:
          runtime: osx-x64
          framework: net5
        run: |
          dotnet publish OpenTabletDriver.Daemon --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
          dotnet publish OpenTabletDriver.Console --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
          dotnet publish OpenTabletDriver.UX.MacOS --configuration Release --runtime $runtime --self-contained false --framework $framework -o build/$runtime
      - name: Copy Configurations
        run: |
          cp -vr ./OpenTabletDriver/Configurations/ build/osx-x64
      - name: Upload MacOS artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver osx-x64
          path: build/osx-x64

  windowspublish:
    runs-on: windows-latest
    name: Windows Publish
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Windows Publish
        env:
          runtime: win-x64
          framework: net5
        run: |
          dotnet publish OpenTabletDriver.Daemon --configuration Release --runtime $ENV:runtime --self-contained false --framework $ENV:framework -o build/$ENV:runtime
          dotnet publish OpenTabletDriver.Console --configuration Release --runtime $ENV:runtime --self-contained false --framework $ENV:framework -o build/$ENV:runtime
          dotnet publish OpenTabletDriver.UX.Wpf --configuration Release --runtime $ENV:runtime --self-contained false --framework $ENV:framework-windows -o build/$ENV:runtime
      - name: Copy Configurations
        run: Copy-Item -Path "./OpenTabletDriver/Configurations/" -Destination "build/win-x64/Configurations/" -Recurse
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver win-x64
          path: build/win-x64
