name: Release

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'The version suffix for this manual build.'
        required: false
  release:
    types: [ published ]
jobs:
  unix:
    runs-on: ubuntu-latest
    name: Unix Release
    env:
      VERSION_SUFFIX: ${{ github.event.inputs.version_suffix }}
    steps:
      - name: Checkout OpenTabletDriver Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Debian Build
        run: ./eng/linux/package.sh --package Debian --output ./dist/debian

      - name: RPM Build
        run: ./eng/linux/package.sh --package RedHat --output ./dist/redhat

      - name: Generic Linux Build
        run: ./eng/linux/package.sh --package BinaryTarBall --output ./dist/tarball

      # - name: MacOS Build
      #   run: ./eng/macos/package --output ./dist/macos

      - name: Upload all artifacts (Release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/debian/*.deb
            ./dist/redhat/*.rpm
            ./dist/tarball/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Debian artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver.deb
          path: ./dist/debian/*.deb

      - name: Upload RPM artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver.rpm
          path: ./dist/redhat/*.rpm

      - name: Upload generic Linux artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver.linux-x64.tar.gz
          path: ./dist/tarball/*.tar.gz

      # - name: Upload macOS artifact (Dispatch)
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: OpenTabletDriver.osx-x64.tar.gz
      #     path: ./dist/macos/*.tar.gz

  windows:
    runs-on: windows-latest
    name: Windows Release
    env:
      VERSION_SUFFIX: ${{ github.event.inputs.version_suffix }}
    steps:
      - name: Checkout OpenTabletDriver Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
          include-prerelease: True

      - name: Package
        run: ./eng/windows/package.ps1

      - name: Upload Windows asset (Release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/OpenTabletDriver.win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows asset (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver.win-x64.zip
          path: ./dist/OpenTabletDriver.win-x64.zip
